# Generated by Django 4.0.4 on 2022-05-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager_panel", "0004_alter_events_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="events",
            name="recipient_uuid",
            field=models.UUIDField(
                blank=True, default=None, verbose_name="UUID получателя"
            ),
            preserve_default=False,
        ),
    ]
