# Generated by Django 4.0.4 on 2022-05-17 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("manager_panel", "0005_events_recipient_uuid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="events",
            old_name="content_id",
            new_name="content_uuid",
        ),
    ]
