# Generated by Django 4.0.4 on 2022-05-17 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("manager_panel", "0006_rename_content_id_events_content_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="events",
            name="source",
            field=models.CharField(
                choices=[
                    ("UGC", "UGC"),
                    ("AUTH", "AUTH"),
                    ("USER", "USER"),
                    ("ADMIN", "ADMIN"),
                ],
                max_length=20,
                verbose_name="Сервис-источник",
            ),
        ),
    ]
